const fs = require('fs');
const path = require('path');

let html = fs.readFileSync(path.join(__dirname, 'site/blog.html'), 'utf-8');

// Find the start of guide-feishu and end of guide-skills (the closing bracket before ];)
const feishuStart = html.indexOf("        id: 'guide-feishu',");
const skillsEnd = html.indexOf("    ];\n  </script>", feishuStart);

if (feishuStart === -1 || skillsEnd === -1) {
  console.error('Could not find guide article boundaries');
  process.exit(1);
}

// Go back to find the opening { of feishu article
let feishuBlockStart = html.lastIndexOf('      {', feishuStart);

const newGuides = `      {
        id: 'guide-feishu',
        category: 'Guides',
        slug: 'how-to-deploy-feishu-ai-bot',
        title: 'Channel Setup: Deploy an AI Bot on Feishu in 10 Minutes',
        title_zh: '渠道配置：10 分钟在飞书上部署 AI 机器人',
        desc: 'Get your App ID and App Secret, import 102 permissions in one click — your AI agent handles messages, docs, spreadsheets, and calendars.',
        desc_zh: '只需获取 App ID 和 App Secret，即可将飞书机器人接入 nexu。支持消息、文档、日历、表格等全部能力。',
        date: "MAR '26",
        date_zh: '2026年3月',
        team: 'TUTORIALS',
        team_zh: '教程',
        label: 'March 2026',
        label_zh: '2026年3月',
        bg: 'url(img/blog-guide-feishu.png) center/cover no-repeat',
        related: ['guide-wechat', 'guide-models', 'guide-skills'],
        sections: [
          { type: 'p', text: 'Only an App ID and App Secret needed to connect a Feishu bot to nexu.' },
          { type: 'h2', text: 'Step 1: Create a Feishu App' },
          { type: 'p', text: 'Go to the <a class="blog-link" href="https://open.feishu.cn/app">Feishu Open Platform</a>, log in, and click "Create Enterprise App."' },
          { type: 'img', src: 'img/docs/feishu-step1-app-list.webp', alt: 'Feishu app list' },
          { type: 'p', text: 'Fill in the app name and description, select an icon, and click "Create."' },
          { type: 'img', src: 'img/docs/feishu-step1-create-app.webp', alt: 'Create enterprise app' },
          { type: 'p', text: 'Go to the "Credentials & Basic Info" page and copy: App ID and App Secret.' },
          { type: 'img', src: 'img/docs/feishu-step1-credentials.webp', alt: 'App ID and App Secret' },
          { type: 'h2', text: 'Step 2: Enter Credentials in nexu' },
          { type: 'p', text: 'Open the nexu desktop client. In the Feishu channel config, paste your App ID and App Secret, click "Connect."' },
          { type: 'img', src: 'img/docs/feishu-step3-nexu-connect.webp', alt: 'Paste credentials in nexu' },
          { type: 'h2', text: 'Step 3: Import App Permissions' },
          { type: 'p', text: 'In the Feishu Open Platform, go to "Permission Management" and click "Batch Import/Export Permissions."' },
          { type: 'img', src: 'img/docs/feishu-step3-permission-management.webp', alt: 'Permission management' },
          { type: 'p', text: 'Select "Import", paste the JSON nexu provides, click "Next, confirm new permissions."' },
          { type: 'img', src: 'img/docs/feishu-step3-paste-json.webp', alt: 'Paste permissions JSON' },
          { type: 'p', text: 'Confirm the permission list (102 total), click "Apply to Enable."' },
          { type: 'img', src: 'img/docs/feishu-step3-confirm-permissions.webp', alt: 'Confirm permissions' },
          { type: 'p', text: 'In the data scope confirmation popup, click "Confirm."' },
          { type: 'img', src: 'img/docs/feishu-step3-data-scope.webp', alt: 'Data scope' },
          { type: 'p', text: 'These permissions cover messaging, doc read/write, calendar management, spreadsheet operations — everything your agent\\'s Skills need.' },
          { type: 'h2', text: 'Step 4: Configure Events & Callbacks' },
          { type: 'p', text: 'Go to "Events & Callbacks", select "Event Configuration" tab.' },
          { type: 'img', src: 'img/docs/feishu-step4-event-config.webp', alt: 'Events page' },
          { type: 'p', text: 'Click edit next to subscription method, select "Use Long Connection to Receive Events", save.' },
          { type: 'img', src: 'img/docs/feishu-step4-event-websocket.webp', alt: 'Long connection' },
          { type: 'p', text: 'Click "Add Event."' },
          { type: 'img', src: 'img/docs/feishu-step4-add-event.webp', alt: 'Add event' },
          { type: 'p', text: 'Search and check: First chat creation (p2p_chat_create), Message received (im.message.receive_v1), Bot added to group (im.chat.member.bot.added_v1), User enters bot chat (im.chat.access_event.bot_p2p_chat_entered_v1). Click "Add."' },
          { type: 'img', src: 'img/docs/feishu-step4-select-event.webp', alt: 'Select events' },
          { type: 'p', text: 'Confirm in the "Added Events" list.' },
          { type: 'img', src: 'img/docs/feishu-step4-event-list.webp', alt: 'Event list' },
          { type: 'p', text: 'Switch to "Callback Configuration" tab, click edit.' },
          { type: 'img', src: 'img/docs/feishu-step4-callback-tab.webp', alt: 'Callback tab' },
          { type: 'p', text: 'Select "Use Long Connection to Receive Callbacks", save.' },
          { type: 'img', src: 'img/docs/feishu-step4-callback-websocket.webp', alt: 'Callback long connection' },
          { type: 'p', text: 'Click "Add Callback."' },
          { type: 'img', src: 'img/docs/feishu-step4-add-callback.webp', alt: 'Add callback' },
          { type: 'p', text: 'Select "Card" category, check "Card Action Trigger" (card.action.trigger), click "Add."' },
          { type: 'img', src: 'img/docs/feishu-step4-select-callback.webp', alt: 'Card action trigger' },
          { type: 'h2', text: 'Step 5: Publish and Test' },
          { type: 'p', text: 'Go to "Version Management & Release."' },
          { type: 'img', src: 'img/docs/feishu-step4-version-manage.webp', alt: 'Version management' },
          { type: 'p', text: 'Click "Create Version", fill in version number and notes, save.' },
          { type: 'img', src: 'img/docs/feishu-step4-create-version.webp', alt: 'Create version' },
          { type: 'p', text: 'Click "Confirm Release", wait for approval.' },
          { type: 'img', src: 'img/docs/feishu-step4-publish.webp', alt: 'Confirm release' },
          { type: 'p', text: 'After approval, click "Chat" in nexu to jump to Feishu and start chatting with your AI bot.' },
          { type: 'img', src: 'img/docs/feishu-step3-connected.webp', alt: 'Feishu connected' },
          { type: 'h2', text: 'FAQ' },
          { type: 'p', text: '<strong>Do I need a public server?</strong> No. nexu uses Feishu\\'s WebSocket long connection — no public IP or callback URLs needed.' },
          { type: 'p', text: '<strong>Why so many permissions?</strong> The 102 permissions map to nexu\\'s Skills (messages, docs, calendars, spreadsheets). For basic chat only, enable just "im:" permissions.' }
        ],
        sections_zh: [
          { type: 'p', text: '只需获取 App ID 和 App Secret，即可将飞书机器人接入 nexu。' },
          { type: 'h2', text: '第一步：创建飞书应用' },
          { type: 'p', text: '打开<a class="blog-link" href="https://open.feishu.cn/app">飞书开放平台</a>，登录你的飞书账号，点击「创建企业自建应用」。' },
          { type: 'img', src: 'img/docs/feishu-step1-app-list.webp', alt: '飞书开放平台应用列表' },
          { type: 'p', text: '填写应用名称、描述，选择图标，点击「创建」。' },
          { type: 'img', src: 'img/docs/feishu-step1-create-app.webp', alt: '创建企业自建应用' },
          { type: 'p', text: '进入「凭证与基础信息」页面，复制以下两个参数：App ID 和 App Secret。' },
          { type: 'img', src: 'img/docs/feishu-step1-credentials.webp', alt: '获取凭证' },
          { type: 'h2', text: '第二步：在 nexu 中填入凭证' },
          { type: 'p', text: '打开 nexu 客户端，在飞书渠道配置中填入 App ID 和 App Secret，点击「Connect」。' },
          { type: 'img', src: 'img/docs/feishu-step3-nexu-connect.webp', alt: '在 nexu 中填入凭证' },
          { type: 'h2', text: '第三步：导入应用权限' },
          { type: 'p', text: '在飞书开放平台，进入你的应用，点击左侧「权限管理」，然后点击「批量导入/导出权限」。' },
          { type: 'img', src: 'img/docs/feishu-step3-permission-management.webp', alt: '权限管理页面' },
          { type: 'p', text: '在弹窗中选择「导入」，将 nexu 提供的 JSON 粘贴到输入框，点击「下一步，确认新增权限」。' },
          { type: 'img', src: 'img/docs/feishu-step3-paste-json.webp', alt: '粘贴权限 JSON' },
          { type: 'p', text: '确认导入的权限列表（共 102 条），点击「申请开通」。' },
          { type: 'img', src: 'img/docs/feishu-step3-confirm-permissions.webp', alt: '确认导入权限' },
          { type: 'p', text: '在弹出的数据范围确认窗口中，点击「确认」完成权限导入。' },
          { type: 'img', src: 'img/docs/feishu-step3-data-scope.webp', alt: '确认数据范围' },
          { type: 'p', text: '这些权限涵盖了消息收发、文档读写、日历管理、电子表格操作等能力，确保 nexu Agent 的各项 Skills 能正常工作。' },
          { type: 'h2', text: '第四步：配置事件与回调' },
          { type: 'p', text: '在飞书开放平台，进入你的应用，点击左侧「事件与回调」，进入「事件配置」tab。' },
          { type: 'img', src: 'img/docs/feishu-step4-event-config.webp', alt: '事件与回调页面' },
          { type: 'p', text: '点击订阅方式旁的编辑按钮，选择「使用长连接接收事件」，点击「保存」。' },
          { type: 'img', src: 'img/docs/feishu-step4-event-websocket.webp', alt: '选择长连接接收事件' },
          { type: 'p', text: '点击「添加事件」。' },
          { type: 'img', src: 'img/docs/feishu-step4-add-event.webp', alt: '添加事件按钮' },
          { type: 'p', text: '在弹窗中搜索并勾选以下事件，点击「添加」：用户和机器人的会话首次被创建 (p2p_chat_create)、接收消息 (im.message.receive_v1)、机器人进群 (im.chat.member.bot.added_v1)、用户进入与机器人的会话 (im.chat.access_event.bot_p2p_chat_entered_v1)。' },
          { type: 'img', src: 'img/docs/feishu-step4-select-event.webp', alt: '选择事件' },
          { type: 'p', text: '添加完成后，可以在「已添加事件」列表中确认。' },
          { type: 'img', src: 'img/docs/feishu-step4-event-list.webp', alt: '已添加事件列表' },
          { type: 'p', text: '切换到「回调配置」tab，点击订阅方式旁的编辑按钮。' },
          { type: 'img', src: 'img/docs/feishu-step4-callback-tab.webp', alt: '回调配置页面' },
          { type: 'p', text: '选择「使用长连接接收回调」，点击「保存」。' },
          { type: 'img', src: 'img/docs/feishu-step4-callback-websocket.webp', alt: '选择长连接接收回调' },
          { type: 'p', text: '点击「添加回调」。' },
          { type: 'img', src: 'img/docs/feishu-step4-add-callback.webp', alt: '添加回调按钮' },
          { type: 'p', text: '在弹窗中选择「卡片」分类，勾选「卡片回传交互」(card.action.trigger)，点击「添加」。' },
          { type: 'img', src: 'img/docs/feishu-step4-select-callback.webp', alt: '选择卡片回传交互' },
          { type: 'h2', text: '第五步：发布应用并测试' },
          { type: 'p', text: '回到飞书开放平台，进入「版本管理与发布」。' },
          { type: 'img', src: 'img/docs/feishu-step4-version-manage.webp', alt: '版本管理与发布' },
          { type: 'p', text: '点击「创建版本」，填写版本号和更新说明，点击「保存」。' },
          { type: 'img', src: 'img/docs/feishu-step4-create-version.webp', alt: '创建版本' },
          { type: 'p', text: '点击「确认发布」，等待审核通过。' },
          { type: 'img', src: 'img/docs/feishu-step4-publish.webp', alt: '确认发布' },
          { type: 'p', text: '等待审核通过后，在 nexu 客户端点击「Chat」即可跳转到飞书与机器人对话 🎉' },
          { type: 'img', src: 'img/docs/feishu-step3-connected.webp', alt: '飞书已连接' },
          { type: 'h2', text: '常见问题' },
          { type: 'p', text: '<strong>需要公网服务器吗？</strong>不需要。nexu 使用飞书长连接（WebSocket）模式，无需公网 IP 或回调地址。' },
          { type: 'p', text: '<strong>为什么需要这么多权限？</strong>这些权限对应 nexu Agent 的各项 Skills（消息、文档、日历、电子表格等）。如果你只需要基础聊天功能，可以只开通 im: 开头的权限。' }
        ]
      },
      {
        id: 'guide-slack',
        category: 'Guides',
        slug: 'how-to-setup-slack-ai-agent',
        title: 'Channel Setup: Set Up an AI Agent in Slack — One-Click App Creation',
        title_zh: '渠道配置：一键创建 Slack AI Agent，零配置上手',
        desc: 'Create a pre-configured Slack app with one link, paste two tokens, and your AI agent is live in every channel — under 5 minutes.',
        desc_zh: '只需获取 Signing Secret 和 Bot Token，即可将 Slack 机器人接入 nexu。',
        date: "MAR '26",
        date_zh: '2026年3月',
        team: 'TUTORIALS',
        team_zh: '教程',
        label: 'March 2026',
        label_zh: '2026年3月',
        bg: 'url(img/blog-guide-slack.png) center/cover no-repeat',
        related: ['guide-discord', 'guide-models', 'guide-skills'],
        sections: [
          { type: 'p', text: 'Only a Signing Secret and Bot Token needed to connect a Slack bot to nexu.' },
          { type: 'h2', text: 'Step 1: Create a Slack App' },
          { type: 'p', text: 'Click the manifest link in nexu\\'s Slack setup guide. This opens Slack\\'s app creation page with all 25+ permissions, event subscriptions, and URLs pre-configured.' },
          { type: 'p', text: 'Select your workspace, click "Next."' },
          { type: 'img', src: 'img/docs/slack-step1-pick-workspace.webp', alt: 'Pick workspace' },
          { type: 'p', text: 'Confirm the pre-configured permissions and URL, click "Create."' },
          { type: 'img', src: 'img/docs/slack-step1-review-create.webp', alt: 'Review and create' },
          { type: 'p', text: 'Click "Got It."' },
          { type: 'img', src: 'img/docs/slack-step1-welcome.webp', alt: 'App created' },
          { type: 'h2', text: 'Step 2: Get Your Signing Secret' },
          { type: 'p', text: 'In the Slack app dashboard, go to "Basic Information" → "App Credentials." Copy the Signing Secret.' },
          { type: 'img', src: 'img/docs/slack-step2-signing-secret.webp', alt: 'Signing Secret' },
          { type: 'h2', text: 'Step 3: Get Your Bot Token' },
          { type: 'p', text: 'Go to "Install App", click "Install to Workspace."' },
          { type: 'img', src: 'img/docs/slack-step3-install-app.webp', alt: 'Install app' },
          { type: 'p', text: 'Click "Allow" on the authorization page.' },
          { type: 'img', src: 'img/docs/slack-step3-authorize.webp', alt: 'Authorize' },
          { type: 'p', text: 'Copy the Bot User OAuth Token.' },
          { type: 'img', src: 'img/docs/slack-step3-bot-token.webp', alt: 'Bot Token' },
          { type: 'h2', text: 'Step 4: Enable Direct Messages' },
          { type: 'p', text: 'Go to "App Home" → "Show Tabs" → "Messages Tab", enable it, and check "Allow users to send Slash commands and messages from the messages tab."' },
          { type: 'img', src: 'img/docs/slack-step4-app-home.webp', alt: 'App Home settings' },
          { type: 'h2', text: 'Step 5: Connect in nexu' },
          { type: 'p', text: 'Paste your Bot User OAuth Token and Signing Secret in nexu\\'s Slack configuration, click "Connect."' },
          { type: 'img', src: 'img/docs/slack-step5-nexu-connect.webp', alt: 'Connect in nexu' },
          { type: 'p', text: 'After connecting, click "Chat" to jump to Slack and start talking to your AI agent.' },
          { type: 'img', src: 'img/docs/slack-step5-connected.webp', alt: 'Slack connected' },
          { type: 'h2', text: 'FAQ' },
          { type: 'p', text: '<strong>Do I need to configure permissions manually?</strong> No. The manifest link pre-configures all scopes and event subscriptions.' },
          { type: 'p', text: '<strong>Do I need a public server?</strong> No. nexu handles event receiving automatically.' }
        ],
        sections_zh: [
          { type: 'p', text: '只需获取 Signing Secret 和 Bot Token，即可将 Slack 机器人接入 nexu。' },
          { type: 'h2', text: '第一步：创建 Slack 应用' },
          { type: 'p', text: '点击 nexu Slack 配置指南中的 manifest 链接，使用预配置的 manifest 一键创建 Slack 应用（权限、事件订阅等已自动配好）。' },
          { type: 'p', text: '选择要安装到的 Workspace，点击「Next」。' },
          { type: 'img', src: 'img/docs/slack-step1-pick-workspace.webp', alt: '选择工作区' },
          { type: 'p', text: '确认预配置的权限和 URL，点击「Create」。' },
          { type: 'img', src: 'img/docs/slack-step1-review-create.webp', alt: '确认创建' },
          { type: 'p', text: '创建成功后，点击「Got It」。' },
          { type: 'img', src: 'img/docs/slack-step1-welcome.webp', alt: '创建成功' },
          { type: 'h2', text: '第二步：获取 Signing Secret' },
          { type: 'p', text: '进入「Basic Information」→「App Credentials」，复制保存 Signing Secret。' },
          { type: 'img', src: 'img/docs/slack-step2-signing-secret.webp', alt: 'Signing Secret' },
          { type: 'h2', text: '第三步：获取 Bot Token' },
          { type: 'p', text: '在侧边栏进入「Install App」，点击「Install to Workspace」。' },
          { type: 'img', src: 'img/docs/slack-step3-install-app.webp', alt: '安装应用' },
          { type: 'p', text: '在授权页面点击「允许」。' },
          { type: 'img', src: 'img/docs/slack-step3-authorize.webp', alt: '授权' },
          { type: 'p', text: '复制保存 Bot User OAuth Token。' },
          { type: 'img', src: 'img/docs/slack-step3-bot-token.webp', alt: 'Bot Token' },
          { type: 'h2', text: '第四步：开启私信' },
          { type: 'p', text: '在侧边栏进入「App Home」，向下找到「Show Tabs」→「Messages Tab」，确认已开启，并勾选「Allow users to send Slash commands and messages from the messages tab」。' },
          { type: 'img', src: 'img/docs/slack-step4-app-home.webp', alt: 'App Home 设置' },
          { type: 'h2', text: '第五步：在 nexu 中填入凭证' },
          { type: 'p', text: '打开 nexu 客户端，在 Slack 渠道配置中填入 Bot User OAuth Token 和 Signing Secret，点击「Connect」。' },
          { type: 'img', src: 'img/docs/slack-step5-nexu-connect.webp', alt: '在 nexu 中连接' },
          { type: 'p', text: '连接成功后，点击「Chat」即可跳转到 Slack 与机器人对话 🎉' },
          { type: 'img', src: 'img/docs/slack-step5-connected.webp', alt: 'Slack 已连接' },
          { type: 'h2', text: '常见问题' },
          { type: 'p', text: '<strong>需要手动配置权限吗？</strong>不需要。通过上方链接创建的应用已自动配置好所有权限和事件订阅。' },
          { type: 'p', text: '<strong>需要公网服务器吗？</strong>不需要。nexu 会自动处理事件接收，无需额外配置回调地址。' }
        ]
      },
      {
        id: 'guide-discord',
        category: 'Guides',
        slug: 'how-to-add-discord-ai-bot',
        title: 'Channel Setup: Add an AI Agent to Discord in 5 Minutes',
        title_zh: '渠道配置：5 分钟把 AI Agent 加入 Discord 服务器',
        desc: 'Create a Discord application, enable Message Content Intent, invite the bot — your AI agent is ready for your community.',
        desc_zh: '只需获取 Application ID 和 Bot Token，即可将 Discord 机器人接入 nexu。',
        date: "MAR '26",
        date_zh: '2026年3月',
        team: 'TUTORIALS',
        team_zh: '教程',
        label: 'March 2026',
        label_zh: '2026年3月',
        bg: 'url(img/blog-guide-discord.png) center/cover no-repeat',
        related: ['guide-slack', 'guide-models', 'guide-skills'],
        sections: [
          { type: 'p', text: 'Only an Application ID and Bot Token needed to connect a Discord bot to nexu.' },
          { type: 'h2', text: 'Step 1: Create a Discord Application' },
          { type: 'p', text: 'Go to the <a class="blog-link" href="https://discord.com/developers/applications">Discord Developer Portal</a>, click "New Application."' },
          { type: 'img', src: 'img/docs/discord-step1-applications.webp', alt: 'Discord applications page' },
          { type: 'p', text: 'Fill in the application name, click "Create."' },
          { type: 'img', src: 'img/docs/discord-step1-create-app.webp', alt: 'Create application' },
          { type: 'p', text: 'Go to "General Information" and copy the Application ID.' },
          { type: 'img', src: 'img/docs/discord-step1-general-info.webp', alt: 'Application ID' },
          { type: 'p', text: 'In the left menu, go to "Bot", click "Reset Token", and copy the Bot Token.' },
          { type: 'img', src: 'img/docs/discord-step3-bot-token.webp', alt: 'Bot Token' },
          { type: 'h2', text: 'Step 2: Connect in nexu' },
          { type: 'p', text: 'Paste your App ID and Bot Token in nexu\\'s Discord configuration, click "Connect."' },
          { type: 'img', src: 'img/docs/discord-step2-nexu-connect.webp', alt: 'Connect in nexu' },
          { type: 'h2', text: 'Step 3: Configure Permissions and Invite' },
          { type: 'p', text: 'Back in the Discord Developer Portal, in "Bot" page, enable "Message Content Intent" under Privileged Gateway Intents.' },
          { type: 'img', src: 'img/docs/discord-step4-intents.webp', alt: 'Message Content Intent' },
          { type: 'p', text: 'Go to "OAuth2" → "URL Generator." Check "bot" and "applications.commands" under Scopes.' },
          { type: 'img', src: 'img/docs/discord-step5-scopes.webp', alt: 'OAuth2 scopes' },
          { type: 'p', text: 'Under Bot Permissions, check: View Channels, Send Messages, Read Message History, Embed Links, Attach Files, Add Reactions, Use External Emojis, Use External Stickers.' },
          { type: 'img', src: 'img/docs/discord-step5-permissions.webp', alt: 'Bot permissions' },
          { type: 'p', text: 'Copy the generated URL at the bottom.' },
          { type: 'img', src: 'img/docs/discord-step5-generated-url.webp', alt: 'Generated URL' },
          { type: 'p', text: 'Open the URL in your browser, select your server, click "Continue."' },
          { type: 'img', src: 'img/docs/discord-step3-select-server.webp', alt: 'Select server' },
          { type: 'p', text: 'Confirm the permissions, click "Authorize."' },
          { type: 'img', src: 'img/docs/discord-step3-authorize.webp', alt: 'Authorize' },
          { type: 'h2', text: 'Step 4: Test' },
          { type: 'p', text: 'After connecting, click "Chat" in nexu to jump to Discord and start chatting with your AI bot.' },
          { type: 'img', src: 'img/docs/discord-step4-connected.webp', alt: 'Discord connected' },
          { type: 'h2', text: 'FAQ' },
          { type: 'p', text: '<strong>Do I need a public server?</strong> No. nexu uses Discord Gateway (WebSocket) — no public IP or callback URLs needed.' },
          { type: 'p', text: '<strong>Bot not responding?</strong> Make sure Message Content Intent is enabled, otherwise the bot cannot read message content.' }
        ],
        sections_zh: [
          { type: 'p', text: '只需获取 Application ID 和 Bot Token，即可将 Discord 机器人接入 nexu。' },
          { type: 'h2', text: '第一步：创建 Discord 应用' },
          { type: 'p', text: '打开 <a class="blog-link" href="https://discord.com/developers/applications">Discord Developer Portal</a>，点击「New Application」。' },
          { type: 'img', src: 'img/docs/discord-step1-applications.webp', alt: 'Discord 应用页面' },
          { type: 'p', text: '填写应用名称，点击「Create」。' },
          { type: 'img', src: 'img/docs/discord-step1-create-app.webp', alt: '创建应用' },
          { type: 'p', text: '进入「General Information」页面，复制保存 Application ID。' },
          { type: 'img', src: 'img/docs/discord-step1-general-info.webp', alt: 'Application ID' },
          { type: 'p', text: '在左侧菜单进入「Bot」，点击「Reset Token」生成 Bot Token，复制保存。' },
          { type: 'img', src: 'img/docs/discord-step3-bot-token.webp', alt: 'Bot Token' },
          { type: 'h2', text: '第二步：在 nexu 中填入凭证' },
          { type: 'p', text: '打开 nexu 客户端，在 Discord 渠道配置中填入 App ID 和 Bot Token，点击「Connect」。' },
          { type: 'img', src: 'img/docs/discord-step2-nexu-connect.webp', alt: '在 nexu 中连接' },
          { type: 'h2', text: '第三步：配置权限并邀请机器人' },
          { type: 'p', text: '回到 Discord Developer Portal，在「Bot」页面下方开启 Privileged Gateway Intents 中的 Message Content Intent。' },
          { type: 'img', src: 'img/docs/discord-step4-intents.webp', alt: 'Message Content Intent' },
          { type: 'p', text: '在左侧菜单进入「OAuth2」→「URL Generator」，勾选 Scopes 中的 bot 和 applications.commands。' },
          { type: 'img', src: 'img/docs/discord-step5-scopes.webp', alt: 'OAuth2 Scopes' },
          { type: 'p', text: '在下方 Bot Permissions 中勾选：View Channels、Send Messages、Read Message History、Embed Links、Attach Files、Add Reactions、Use External Emojis、Use External Stickers。' },
          { type: 'img', src: 'img/docs/discord-step5-permissions.webp', alt: 'Bot 权限' },
          { type: 'p', text: '复制页面底部生成的 URL。' },
          { type: 'img', src: 'img/docs/discord-step5-generated-url.webp', alt: '生成的 URL' },
          { type: 'p', text: '在浏览器中打开该 URL，选择你的服务器，点击「Continue」。' },
          { type: 'img', src: 'img/docs/discord-step3-select-server.webp', alt: '选择服务器' },
          { type: 'p', text: '确认权限列表，点击「Authorize」，授权机器人加入。' },
          { type: 'img', src: 'img/docs/discord-step3-authorize.webp', alt: '授权' },
          { type: 'h2', text: '第四步：测试' },
          { type: 'p', text: '连接成功后，在 nexu 客户端点击「Chat」即可跳转到 Discord 与机器人对话 🎉' },
          { type: 'img', src: 'img/docs/discord-step4-connected.webp', alt: 'Discord 已连接' },
          { type: 'h2', text: '常见问题' },
          { type: 'p', text: '<strong>需要公网服务器吗？</strong>不需要。nexu 使用 Discord Gateway（WebSocket），无需公网 IP 或回调地址。' },
          { type: 'p', text: '<strong>机器人没有回复消息？</strong>请确认已开启 Message Content Intent，否则机器人无法读取消息内容。' }
        ]
      },
      {
        id: 'guide-models',
        category: 'Guides',
        slug: 'how-to-configure-ai-models-nexu',
        title: 'Model Setup: Claude, GPT & Gemini in One Client',
        title_zh: '模型配置：Claude、GPT、Gemini 一个客户端搞定',
        desc: 'Free hosted models or bring your own API key — switch between Claude, GPT, Gemini, and more with one click, no workflow disruption.',
        desc_zh: 'nexu 支持两种模型接入方式：Nexu Official（登录即用）和 BYOK（自带 API Key）。两种方式可随时切换。',
        date: "MAR '26",
        date_zh: '2026年3月',
        team: 'TUTORIALS',
        team_zh: '教程',
        label: 'March 2026',
        label_zh: '2026年3月',
        bg: 'url(img/blog-guide-models.png) center/cover no-repeat',
        related: ['guide-skills', 'guide-wechat', 'featured'],
        sections: [
          { type: 'p', text: 'nexu supports two model access methods: Nexu Official (hosted, login to use) and BYOK (bring your own API Key). Both can be switched at any time without affecting existing conversations or channel connections.' },
          { type: 'h2', text: 'Step 1: Open Settings' },
          { type: 'p', text: 'Click "Settings" in the left navigation bar to enter the AI Model Providers page.' },
          { type: 'img', src: 'img/docs/nexu-settings-open.webp', alt: 'Settings page' },
          { type: 'h2', text: 'Option A — Nexu Official (Recommended)' },
          { type: 'p', text: 'Select "Nexu Official" in the provider list, click "Sign in to Nexu." After logging in, Claude Sonnet 4.6, Claude Opus 4.6, Claude Haiku 4.5 and more are immediately available — no API key configuration needed.' },
          { type: 'img', src: 'img/docs/nexu-models-official.webp', alt: 'Nexu Official models' },
          { type: 'h2', text: 'Option B — Bring Your Own Key (BYOK)' },
          { type: 'p', text: 'Select Anthropic, OpenAI, Google AI, or another provider. Paste your API key, optionally modify the API Proxy URL, click "Save." nexu auto-validates and loads available models. Your key stays on your local machine — it never touches nexu\\'s servers.' },
          { type: 'img', src: 'img/docs/nexu-models-byok.webp', alt: 'BYOK configuration' },
          { type: 'h2', text: 'Step 3: Select Active Model' },
          { type: 'p', text: 'In the "Nexu Bot Model" dropdown at the top, select the model for your agent. Switch across providers anytime — mid-project — without affecting existing conversations.' },
          { type: 'img', src: 'img/docs/nexu-model-select.webp', alt: 'Model selector' },
          { type: 'h2', text: 'Supported Providers' },
          { type: 'p', text: 'Anthropic (Claude, sk-ant-...) · OpenAI (GPT, sk-...) · Google AI (Gemini, AIza...) · xAI (Grok, xai-...) · Custom (any OpenAI-compatible endpoint for self-hosted models or proxies).' },
          { type: 'h2', text: 'Best Practices' },
          { type: 'p', text: 'Use minimum-privilege API keys. Never expose keys in screenshots, tickets, or git commits. Click "Verify Connection" before saving a BYOK provider. Use Custom provider type for proxies, self-hosted gateways, or OpenAI-compatible inference services.' },
          { type: 'h2', text: 'FAQ' },
          { type: 'p', text: '<strong>Which method should I start with?</strong> Nexu Official — log in and use high-quality models instantly, zero configuration.' },
          { type: 'p', text: '<strong>Can I configure multiple BYOK providers?</strong> Yes. Anthropic, OpenAI, Google AI etc. can be configured independently and switched via the top model dropdown.' },
          { type: 'p', text: '<strong>Does my API key get uploaded to nexu servers?</strong> No. API keys are stored only on your local device.' }
        ],
        sections_zh: [
          { type: 'p', text: 'nexu 支持两种模型接入方式：Nexu Official（托管模型，登录即用）和 BYOK（自带 API Key）。两种方式可随时切换，不影响已有对话和渠道连接。' },
          { type: 'h2', text: '第一步：打开 Settings' },
          { type: 'p', text: '在 nexu 客户端左侧导航栏点击 Settings，进入 AI Model Providers 配置页面。' },
          { type: 'img', src: 'img/docs/nexu-settings-open.webp', alt: 'Settings 页面' },
          { type: 'h2', text: '方式 A — Nexu Official（推荐）' },
          { type: 'p', text: '在左侧供应商列表中选择 Nexu Official，点击 Sign in to Nexu 完成账号登录。登录后无需配置任何 API Key，Claude Sonnet 4.6、Claude Opus 4.6、Claude Haiku 4.5 等模型立即可用。' },
          { type: 'img', src: 'img/docs/nexu-models-official.webp', alt: 'Nexu Official 模型' },
          { type: 'h2', text: '方式 B — 自带密钥（BYOK）' },
          { type: 'p', text: '在左侧供应商列表中选择 Anthropic、OpenAI、Google AI 或其他供应商：在 API Key 字段粘贴你的密钥；如需自定义代理，修改 API Proxy URL；点击 Save，nexu 会自动验证密钥并加载可用模型列表。' },
          { type: 'img', src: 'img/docs/nexu-models-byok.webp', alt: 'BYOK 配置' },
          { type: 'h2', text: '第三步：选择当前模型' },
          { type: 'p', text: '连接成功后，在 Settings 页面顶部 Nexu Bot Model 下拉菜单中选择 Agent 使用的模型，支持跨供应商随时切换。' },
          { type: 'img', src: 'img/docs/nexu-model-select.webp', alt: '模型选择' },
          { type: 'h2', text: '支持的供应商' },
          { type: 'p', text: 'Anthropic (sk-ant-...) · OpenAI (sk-...) · Google AI (AIza...) · xAI (xai-...) · Custom（你的 OpenAI 兼容端点）。' },
          { type: 'h2', text: '使用建议' },
          { type: 'p', text: '使用最小权限的 API Key，避免不必要的访问范围。不要在截图、工单或 Git 提交记录中暴露密钥。添加 BYOK 供应商时，先点击 Verify Connection 验证连通性，确认无误后再保存。需要代理、自建网关或 OpenAI 兼容推理服务时，使用 Custom 供应商类型。' },
          { type: 'h2', text: '常见问题' },
          { type: 'p', text: '<strong>刚开始用哪种方式比较好？</strong>推荐 Nexu Official——登录账号后无需任何配置，即可使用高质量模型。' },
          { type: 'p', text: '<strong>可以同时配置多个 BYOK 供应商吗？</strong>可以。Anthropic、OpenAI、Google AI 等可以独立配置，随时通过顶部 Nexu Bot Model 下拉菜单切换。' },
          { type: 'p', text: '<strong>API Key 会被上传到 nexu 服务器吗？</strong>不会。API Key 仅存储在你的本地设备上，不会传输至 nexu 服务器。' }
        ]
      },
      {
        id: 'guide-skills',
        category: 'Guides',
        slug: 'how-to-install-ai-agent-skills',
        title: 'Skill Setup: Turn Your Chatbot Into a Specialist',
        title_zh: '技能安装：把聊天机器人变成专家',
        desc: 'Browse, one-click install, start using — Skills give your AI agent specialized capabilities from document generation to spreadsheet operations, no restart needed.',
        desc_zh: '技能扩展了 Agent 的能力边界——从网络搜索、文档生成，到飞书多维表格操作、第三方 API 调用，应有尽有。安装只需几秒钟。',
        date: "MAR '26",
        date_zh: '2026年3月',
        team: 'TUTORIALS',
        team_zh: '教程',
        label: 'March 2026',
        label_zh: '2026年3月',
        bg: 'url(img/blog-guide-skills.png) center/cover no-repeat',
        related: ['guide-models', 'guide-wechat', 'featured'],
        sections: [
          { type: 'p', text: 'Skills extend your agent\\'s capabilities — from web search and document generation to Feishu Bitable operations and third-party API calls. Installing a skill takes seconds.' },
          { type: 'h2', text: 'Step 1: Open the Skills Page' },
          { type: 'p', text: 'Click "Skills" in the left navigation bar to enter the Skill center. The "Explore" tab shows all available public skills, filterable by category (Office & Collaboration, Files & Knowledge, Creative & Design, Business Analysis, Audio & Video, etc.) or keyword search.' },
          { type: 'img', src: 'img/docs/nexu-skills.webp', alt: 'Skills page' },
          { type: 'h2', text: 'Step 2: Find and Install a Skill' },
          { type: 'p', text: 'Browse or search for your target skill. Click "Install" on the card. Skills support hot-loading — they activate immediately without restarting your agent.' },
          { type: 'img', src: 'img/docs/nexu-skills-search.webp', alt: 'Search and install skills' },
          { type: 'h2', text: 'Step 3: Verify Installation' },
          { type: 'p', text: 'Switch to the "Yours" tab to see installed skills. Each has a toggle to enable or disable without uninstalling.' },
          { type: 'img', src: 'img/docs/nexu-skills-installed.webp', alt: 'Installed skills' },
          { type: 'h2', text: 'Step 4: Use Skills in Conversation' },
          { type: 'p', text: 'After installation, just describe what you need in your channel conversation. Your agent automatically selects the right skill to complete the task.' },
          { type: 'img', src: 'img/docs/nexu-skills-chat.webp', alt: 'Skills in conversation' },
          { type: 'h2', text: 'FAQ' },
          { type: 'p', text: '<strong>Do I need to restart after installing?</strong> No. Skills support hot-loading — the agent recognizes and enables new skills immediately.' },
          { type: 'p', text: '<strong>Can I install custom skills?</strong> Yes. nexu supports local custom skill development. See the developer docs for details.' },
          { type: 'p', text: '<strong>How to uninstall?</strong> Go to the "Yours" tab and click "Uninstall" next to the skill.' }
        ],
        sections_zh: [
          { type: 'p', text: '技能扩展了 Agent 的能力边界——从网络搜索、文档生成，到飞书多维表格操作、第三方 API 调用，应有尽有。安装一个技能只需几秒钟。' },
          { type: 'h2', text: '第一步：打开技能页面' },
          { type: 'p', text: '在 nexu 客户端左侧导航栏点击 Skills，进入技能中心。Explore 标签展示所有可安装的公共技能，支持按分类筛选（Office & Collaboration、Files & Knowledge、Creative & Design、Business Analysis、Audio & Video 等）或直接搜索关键词。' },
          { type: 'img', src: 'img/docs/nexu-skills.webp', alt: '技能页面' },
          { type: 'h2', text: '第二步：找到并安装技能' },
          { type: 'p', text: '浏览或搜索目标技能，点击卡片上的 Install 按钮。技能支持热加载，安装后无需重启 Agent 即可立即生效。' },
          { type: 'img', src: 'img/docs/nexu-skills-search.webp', alt: '搜索安装技能' },
          { type: 'h2', text: '第三步：确认安装' },
          { type: 'p', text: '切换到 Yours 标签，查看已安装的技能列表，并可通过开关随时启用或禁用单个技能。' },
          { type: 'img', src: 'img/docs/nexu-skills-installed.webp', alt: '已安装技能' },
          { type: 'h2', text: '第四步：在对话中使用' },
          { type: 'p', text: '技能安装后，直接在渠道对话中描述需求即可，Agent 会自动选择合适的技能完成任务。' },
          { type: 'img', src: 'img/docs/nexu-skills-chat.webp', alt: '对话中使用技能' },
          { type: 'h2', text: '常见问题' },
          { type: 'p', text: '<strong>安装技能后需要重启 Agent 吗？</strong>不需要。技能支持热加载，Agent 会立即识别并启用新安装的技能。' },
          { type: 'p', text: '<strong>可以安装目录以外的技能吗？</strong>可以。nexu 支持本地自定义技能开发，满足个性化需求。详见开发者文档。' },
          { type: 'p', text: '<strong>如何卸载技能？</strong>进入 Yours 标签，点击对应技能旁的 Uninstall 即可。' }
        ]
      }`;

// Replace from feishuBlockStart to the end of guide-skills (before the closing ];)
const beforeGuides = html.substring(0, feishuBlockStart);
const afterGuides = html.substring(skillsEnd);

html = beforeGuides + newGuides + afterGuides;

fs.writeFileSync(path.join(__dirname, 'site/blog.html'), html, 'utf-8');
console.log('Done. All 5 guide articles replaced with full docs content.');
