const fs = require('fs');
const path = require('path');

let html = fs.readFileSync(path.join(__dirname, 'site/blog.html'), 'utf-8');

const arrStart = html.indexOf('window._blogArticles = [');
const guideWechatStart = html.indexOf("        id: 'guide-wechat',");
const blockStart = html.lastIndexOf('      {', guideWechatStart);

const before = html.substring(0, arrStart);
const after = html.substring(blockStart);

const newArticles = `window._blogArticles = [
      {
        id: 'featured',
        category: 'Announcements',
        slug: 'nexu-open-source-openclaw-desktop-client',
        title: 'nexu: The Simplest Open-Source OpenClaw Desktop Client for WeChat & Feishu',
        title_zh: 'nexu：最简单的微信 & 飞书 OpenClaw 开源桌面客户端',
        desc: 'An open-source desktop client that runs your OpenClaw Agent in WeChat, Feishu, Slack & Discord. Double-click install, BYOK, local-first. Top-tier models free during beta.',
        desc_zh: '开源桌面客户端，让你的 OpenClaw Agent 在微信、飞书、Slack、Discord 里直接运行。双击安装、自带 Key、数据本地优先。公测期间顶级模型完全免费。',
        date: "MAR 23 '26",
        date_zh: '2026年3月23日',
        team: 'PRODUCT TEAM',
        team_zh: '产品团队',
        label: 'March 2026',
        label_zh: '2026年3月',
        bg: 'url(img/blog-featured.png) center/cover no-repeat',
        featured: true,
        related: ['ann-v015', 'ann-v014', 'ann-v010'],
        sections: [
          { type: 'p', text: '<strong>nexu</strong> (next to you) is an open-source desktop client that runs your <strong>OpenClaw 🦞</strong> Agent directly inside WeChat, Feishu, Slack, Discord, and other IM channels.' },
          { type: 'p', text: '<strong>WeChat + OpenClaw supported</strong> — works with WeChat 8.0.7 OpenClaw plugin. Click connect, scan with WeChat, and start chatting with your AI Agent.' },
          { type: 'p', text: '<strong>Download and go</strong> — graphical setup, built-in Feishu Skills, multi-model support (Claude / GPT / Gemini and more), and bring your own API Key.' },
          { type: 'p', text: 'Once connected to IM, your Agent is online 24/7 — chat from your phone anytime, anywhere. All data stays on your machine. Your privacy, fully in your control.' },
          { type: 'p', text: '🎉 <strong>Beta Perk</strong>: During the beta period, top-tier models like Claude, GPT, Gemini, Kimi, GLM, and more are <strong>completely free with unlimited usage</strong>. <a class="blog-link" href="https://nexu.io">Download and try now →</a>' },
          { type: 'h2', text: 'Difference from Other Solutions' },
          { type: 'p', text: '<strong>Models:</strong> OpenClaw official requires manual config. Hosted stacks lock you to one platform. nexu lets you pick Claude / GPT / Gemini etc. — one-click switch in GUI.' },
          { type: 'p', text: '<strong>Data path:</strong> OpenClaw is local. Hosted stacks route through vendor servers. nexu is local-first — we don\\'t host your business data.' },
          { type: 'p', text: '<strong>Cost:</strong> OpenClaw is free but self-deploy. Hosted stacks charge subscriptions. nexu client is free — pay providers via your own API keys.' },
          { type: 'p', text: '<strong>Source:</strong> OpenClaw is open source. Hosted stacks are closed. nexu is MIT — fork and audit.' },
          { type: 'p', text: '<strong>Channels:</strong> OpenClaw requires DIY integration. Hosted stacks vary. nexu has built-in WeChat, Feishu, Slack, Discord — works out of the box.' },
          { type: 'p', text: '<strong>Interface:</strong> OpenClaw is CLI. nexu is pure GUI — no CLI needed, double-click to start.' },
          { type: 'h2', text: 'Features' },
          { type: 'p', text: '<strong>🖱 Double-click install</strong> — Download, double-click, start using. No environment variables, no dependency wrestling, no long install docs. nexu\\'s first run is as capable as it gets — ready out of the box.' },
          { type: 'p', text: '<strong>🔗 Built-in OpenClaw 🦞 Skills + full Feishu Skills</strong> — Native OpenClaw 🦞 Skills and full Feishu Skills ship together. Agents move beyond demos and into the real workflows your team already uses — without extra integration work.' },
          { type: 'p', text: '<strong>🧠 Top-tier models, out of the box</strong> — Use Claude 4.6, ChatGPT 5.4, Minimax 2.5, GLM 5.0, Kimi 2.5, and more directly via your nexu account. No extra config. Switch to your own API Key anytime.' },
          { type: 'p', text: '<strong>🔑 Bring your own API Key, no login</strong> — Prefer your own model providers? Add your API Key and use the client without creating an account or logging in.' },
          { type: 'p', text: '<strong>📱 IM-connected, mobile-ready</strong> — Connect to WeChat, Feishu, Slack, or Discord and your AI agent is instantly available on your phone. No extra app — just open WeChat or your team chat and start talking to your agent on the go.' },
          { type: 'p', text: '<strong>👥 Built for teams</strong> — Open-source at the core, with a desktop experience that actually runs. Compatible with the tools and model stack your team already trusts.' },
          { type: 'h2', text: 'Use Cases' },
          { type: 'p', text: 'nexu is built for <strong>One Person Company</strong> and small teams — one person, one AI team.' },
          { type: 'p', text: '<strong>🛒 Solo e-commerce / cross-border trade</strong> — "I used to spend the whole weekend writing listings in 3 languages. Now I tell my Agent the product specs in Feishu, and by the time I finish my coffee, the listings are ready for Amazon, Shopee, and TikTok Shop." Product research, competitor pricing, listing optimization, multilingual marketing assets — compress a week\\'s work into one afternoon.' },
          { type: 'p', text: '<strong>✍️ Content creators / knowledge bloggers</strong> — "Monday morning: I ask my Agent in Slack for this week\\'s trending topics. By lunch, I have 5 draft posts across Xiaohongshu, WeChat, and Twitter — each in the right tone for the platform." Trend tracking, topic generation, multi-platform content production, comment engagement — run a content matrix solo.' },
          { type: 'p', text: '<strong>💻 Indie developers</strong> — "3 AM bug hunt? I paste the stack trace into Discord, my Agent traces it to a race condition, suggests a fix, and even drafts the PR description. Pair programming that never sleeps." Code review, doc generation, bug analysis, repetitive task automation — your Agent is your pair-programming partner.' },
          { type: 'p', text: '<strong>⚖️ Legal / finance / consulting</strong> — "A client sends a 40-page contract on Feishu. I forward it to my Agent — 10 minutes later I get a risk summary, flagged clauses, and suggested revisions. What used to take half a day now takes a coffee break." Contract review, regulation lookup, report generation, client Q&A — turn domain expertise into Agent skills.' },
          { type: 'p', text: '<strong>🏪 Local business / retail</strong> — "Customers message me at midnight asking \\'is this in stock?\\' My Agent in Feishu auto-replies with real-time inventory, handles returns, and even sends a promo coupon. I actually sleep now." Inventory management, order follow-up, auto-reply to customer messages, marketing copy — let AI help run the shop.' },
          { type: 'p', text: '<strong>🎨 Design / creative</strong> — "I drop a rough brief in Slack: \\'landing page for a pet food brand, playful vibe.\\' My Agent comes back with copy options, color palette suggestions, and reference images — all before the kickoff meeting." Requirement breakdown, asset search, copywriting, design annotation — free up creative time, cut repetitive work.' },
          { type: 'h2', text: 'Getting Started' },
          { type: 'p', text: '<strong>System requirements:</strong> macOS 12+ (Apple Silicon), ~500 MB storage. Windows & macOS Intel in development.' },
          { type: 'p', text: 'Go to <a class="blog-link" href="https://nexu.io">nexu.io</a> or <a class="blog-link" href="https://github.com/nexu-io/nexu/releases">GitHub Releases</a>, download the Mac installer, and launch nexu. Sign in with your nexu account for instant access to supported models, or add your own API Key and use the client without an account.' },
          { type: 'h2', text: 'Open Source' },
          { type: 'p', text: 'nexu is open-sourced under the <strong>MIT License</strong> — free to use, modify, distribute, and build upon for any purpose, including commercial use. We believe open source is the future of AI infrastructure. Fork it, contribute, or build your own product on top of nexu.' },
          { type: 'p', text: 'Explore the code and contribute on <a class="blog-link" href="https://github.com/nexu-io/nexu" target="_blank">GitHub</a>.' }
        ],
        sections_zh: [
          { type: 'p', text: '<strong>nexu</strong>（奈苏，next to you）是一个开源桌面客户端，让你的 <strong>OpenClaw 🦞</strong> Agent 直接运行在微信、飞书、Slack、Discord 等 IM 中。' },
          { type: 'p', text: '<strong>已支持微信接入 OpenClaw</strong> —— 适配微信 8.0.7 OpenClaw 插件，点击连接、微信扫码，即可在微信中与 AI Agent 对话。' },
          { type: 'p', text: '下载即用，图形化配置，内置飞书 Skills，支持 Claude / GPT / Gemini 等多模型与自带 API Key。' },
          { type: 'p', text: '连接 IM 后，Agent 7×24 小时在线——手机上随时对话，不受桌面限制。所有数据保存在本机，隐私安全，完全可控。' },
          { type: 'p', text: '🎉 <strong>内测福利</strong>：内测期间，Claude、GPT、Gemini、Kimi、GLM 等顶级模型<strong>全部免费、无限量使用</strong>。<a class="blog-link" href="https://nexu.io">立即下载体验 →</a>' },
          { type: 'h2', text: '与常见方案的区别' },
          { type: 'p', text: '<strong>模型：</strong>OpenClaw 官方自选但需手动配置。托管方案平台指定不可更换。nexu 自选 Claude / GPT / Gemini 等，GUI 一键切换。' },
          { type: 'p', text: '<strong>数据路径：</strong>OpenClaw 本地。托管方案经第三方服务器，数据不可控。nexu 本机为主，不托管你的业务数据。' },
          { type: 'p', text: '<strong>费用：</strong>OpenClaw 免费但需自行部署。托管方案订阅/按席收费。nexu 客户端免费，按自备 API Key 计费。' },
          { type: 'p', text: '<strong>源码：</strong>OpenClaw 开源。托管方案闭源无法审计。nexu MIT 开源，可 fork、可审计。' },
          { type: 'p', text: '<strong>渠道：</strong>OpenClaw 需自行对接。托管方案视产品而定常有限制。nexu 内置微信、飞书、Slack、Discord，开箱即用。' },
          { type: 'p', text: '<strong>使用方式：</strong>OpenClaw 是 CLI 需技术背景。nexu 纯 GUI，无需 CLI，双击即用。' },
          { type: 'h2', text: '功能要点' },
          { type: 'p', text: '<strong>🖱 双击安装</strong> —— 下载、双击、开始使用。无需环境变量、无需折腾依赖、无需长文档。nexu 的首次体验与能力一致——开箱即用。' },
          { type: 'p', text: '<strong>🔗 内置 OpenClaw 🦞 Skills + 完整飞书 Skills</strong> —— 原生 OpenClaw 🦞 Skills 与完整飞书 Skills 一并提供。Agent 不再停留在演示，而是直接进入团队真实工作流，无需额外集成。' },
          { type: 'p', text: '<strong>🧠 顶级模型，开箱即用</strong> —— 通过 nexu 账号直接使用 Claude 4.6、ChatGPT 5.4、Minimax 2.5、GLM 5.0、Kimi 2.5 等模型，无需额外配置。也可随时切换为自带 API Key。' },
          { type: 'p', text: '<strong>🔑 支持自带 API Key，无需登录</strong> —— 更倾向自己的模型服务？填入 API Key 即可使用，无需注册、无需登录。' },
          { type: 'p', text: '<strong>📱 连接 IM，移动端即用</strong> —— 连接微信、飞书、Slack 或 Discord，你的 AI Agent 立刻出现在手机上。无需额外 App——打开微信或团队聊天工具，随时随地和 Agent 对话。' },
          { type: 'p', text: '<strong>👥 为团队而生</strong> —— 核心开源，同时提供真正可用的桌面体验，兼容团队已有的工具与模型栈。' },
          { type: 'h2', text: '使用场景' },
          { type: 'p', text: 'nexu 面向 <strong>One Person Company</strong> 与小团队，让一个人就能拥有一支 AI 团队。' },
          { type: 'p', text: '<strong>🛒 一人电商 / 跨境电商</strong> —— "以前写 3 种语言的商品详情要花整个周末。现在我在飞书里把产品参数发给 Agent，一杯咖啡的功夫，亚马逊、Shopee、TikTok Shop 的 listing 就全好了。" 选品调研、竞品比价、商品标题优化、多语言营销素材生成——从一周压缩到一个下午。' },
          { type: 'p', text: '<strong>✍️ 知识博主 / 自媒体</strong> —— "周一早上，我在 Slack 里问 Agent 这周有什么热点。午饭前，小红书、公众号、Twitter 的 5 篇初稿就出来了——每篇都是对应平台的调性。" 热点追踪、选题生成、多平台内容批量产出、评论区互动——一个人运营矩阵账号。' },
          { type: 'p', text: '<strong>💻 独立开发者</strong> —— "凌晨 3 点排 Bug？我把报错堆栈贴到 Discord，Agent 定位到一个竞态条件，给出修复方案，连 PR 描述都帮我写好了。永不下线的结对编程。" 代码审查、文档生成、Bug 分析、重复任务自动化——Agent 就是你的结对编程搭档。' },
          { type: 'p', text: '<strong>⚖️ 法律 / 财税 / 咨询</strong> —— "客户在飞书发来一份 40 页合同。我转发给 Agent——10 分钟后收到风险摘要、标记条款和修改建议。以前半天的活儿，现在一杯咖啡的时间。" 合同审阅、法规检索、报表生成、客户问答——把专业知识变成 Agent 的技能。' },
          { type: 'p', text: '<strong>🏪 门店 / 本地商家</strong> —— "半夜客户发消息问'这个还有货吗？'我飞书里的 Agent 自动回复实时库存，处理退换，还顺手发了张优惠券。我终于能安心睡觉了。" 库存管理、订单跟进、客户消息自动回复、营销文案生成——让 AI 帮你看店。' },
          { type: 'p', text: '<strong>🎨 设计 / 创意</strong> —— "我在 Slack 里丢了一句简单的 brief：'宠物食品品牌落地页，活泼风格。'Agent 回了文案方案、配色建议和参考图——全在启动会之前搞定。" 需求拆解、素材检索、文案撰写、设计稿标注——释放创意时间，减少重复劳动。' },
          { type: 'h2', text: '快速开始' },
          { type: 'p', text: '<strong>系统要求：</strong>macOS 12+（Apple Silicon），约 500 MB 磁盘空间。Windows 与 macOS Intel 开发中。' },
          { type: 'p', text: '打开 <a class="blog-link" href="https://nexu.io">nexu 官网</a>或 <a class="blog-link" href="https://github.com/nexu-io/nexu/releases">GitHub Releases</a>，下载 Mac 安装包并启动 nexu。使用 nexu 账号登录，立即使用已支持的模型；也可添加自带 API Key，无需账号即可使用。' },
          { type: 'h2', text: '开源协议' },
          { type: 'p', text: 'nexu 基于 <strong>MIT License</strong> 开源——你可以自由使用、修改、分发，包括商业用途。我们相信开源是 AI 基础设施的未来。欢迎 fork、贡献、或基于 nexu 构建你自己的产品。' },
          { type: 'p', text: '在 <a class="blog-link" href="https://github.com/nexu-io/nexu" target="_blank">GitHub</a> 上探索代码和参与贡献。' }
        ]
      },
      {
        id: 'ann-v010',
        category: 'Announcements',
        slug: 'nexu-v010-first-release',
        title: 'nexu v0.1.0: The First Public Release Is Here',
        title_zh: 'nexu v0.1.0：首个公开版本正式发布',
        desc: 'The first public release of nexu — a double-click-install OpenClaw desktop client with built-in Skills, top-tier models, and BYOK support.',
        desc_zh: 'nexu 首个公开版本正式发布——双击安装即可使用的 OpenClaw 桌面客户端，内置丰富 Skills 和主流大模型。',
        date: "MAR 18 '26",
        date_zh: '2026年3月18日',
        team: 'ENGINEERING',
        team_zh: '工程团队',
        label: 'March 2026',
        label_zh: '2026年3月',
        bg: 'url(img/blog-release-v010.png) center/cover no-repeat',
        related: ['ann-v014', 'featured', 'ann-nightly'],
        sections: [
          { type: 'p', text: 'The first public release of <strong>nexu</strong> — The Simplest OpenClaw Desktop for OPC.' },
          { type: 'h2', text: 'Highlights' },
          { type: 'p', text: '<strong>Double-click install</strong> — Download, launch, and start using AI agents in seconds. No terminal, no config files.' },
          { type: 'p', text: '<strong>Built-in OpenClaw Skills + full Feishu Skills</strong> — Native skill integrations ship out of the box, plugging directly into your team\\'s existing workflows.' },
          { type: 'p', text: '<strong>Top-tier models, ready to go</strong> — Access Claude 4.6, ChatGPT 5.4, Minimax 2.5, GLM 5.0, Kimi 2.5, and more via your Nexu account.' },
          { type: 'p', text: '<strong>Bring your own API Key</strong> — Use your own model providers without creating an account or logging in.' },
          { type: 'p', text: '<strong>Desktop client for macOS</strong> — A native Electron-based desktop experience built for real daily use.' },
          { type: 'h2', text: 'What\\'s Included' },
          { type: 'p', text: 'Web frontend + Backend API + Landing page. Desktop client (macOS, Apple Silicon). Gateway & Router services. OpenClaw core runtime. Built-in skill system (local dev & bot skills). Deployment configs (Helm, K8s, Nginx).' },
          { type: 'h2', text: 'System Requirements' },
          { type: 'p', text: 'OS: macOS 12+ (Apple Silicon). Storage: ~500 MB.' },
          { type: 'p', text: 'Windows & macOS Intel support is in development.' },
          { type: 'h2', text: 'Get Started' },
          { type: 'p', text: 'Download the Mac client from this release, or visit <a class="blog-link" href="https://nexu.io">nexu.io</a> for more information.' },
          { type: 'p', text: 'Full Changelog: <a class="blog-link" href="https://github.com/nexu-io/nexu/commits/v0.1.0">github.com/nexu-io/nexu/commits/v0.1.0</a>' }
        ],
        sections_zh: [
          { type: 'p', text: '<strong>nexu</strong> 首个公开版本——最简单的 OpenClaw 桌面客户端，面向 One Person Company。' },
          { type: 'h2', text: '亮点' },
          { type: 'p', text: '<strong>双击安装</strong>——下载、启动，几秒内开始使用 AI Agent。无需终端，无需配置文件。' },
          { type: 'p', text: '<strong>内置 OpenClaw Skills + 完整飞书 Skills</strong>——原生技能集成开箱即用，直接对接团队现有工作流。' },
          { type: 'p', text: '<strong>顶级模型，即开即用</strong>——通过 nexu 账号直接使用 Claude 4.6、ChatGPT 5.4、Minimax 2.5、GLM 5.0、Kimi 2.5 等。' },
          { type: 'p', text: '<strong>支持自带 API Key</strong>——使用自己的模型供应商，无需注册、无需登录。' },
          { type: 'p', text: '<strong>macOS 桌面客户端</strong>——基于 Electron 的原生桌面体验，为日常使用而生。' },
          { type: 'h2', text: '包含内容' },
          { type: 'p', text: 'Web 前端 + 后端 API + Landing 页面。桌面客户端（macOS，Apple Silicon）。网关 & 路由服务。OpenClaw 核心运行时。内置技能系统（本地开发 & 机器人技能）。部署配置（Helm、K8s、Nginx）。' },
          { type: 'h2', text: '系统要求' },
          { type: 'p', text: '系统：macOS 12+（Apple Silicon）。磁盘：约 500 MB。' },
          { type: 'p', text: 'Windows 与 macOS Intel 支持开发中。' },
          { type: 'h2', text: '开始使用' },
          { type: 'p', text: '从本次发布下载 Mac 客户端，或访问 <a class="blog-link" href="https://nexu.io">nexu.io</a> 了解更多。' },
          { type: 'p', text: '完整变更日志：<a class="blog-link" href="https://github.com/nexu-io/nexu/commits/v0.1.0">github.com/nexu-io/nexu/commits/v0.1.0</a>' }
        ]
      },
      {
        id: 'ann-nightly',
        category: 'Announcements',
        slug: 'nexu-nightly-builds-live',
        title: 'nexu v0.1.3 Nightly: Automated Test Builds Are Live',
        title_zh: 'nexu v0.1.3 Nightly：自动化测试构建上线',
        desc: 'nexu now ships automated nightly test builds — notarized, stapled, and ready for early testing.',
        desc_zh: 'nexu 上线了自动化 Nightly 测试构建——经过 Apple 公证，测试者可以第一时间下载试用。',
        date: "MAR 17 '26",
        date_zh: '2026年3月17日',
        team: 'ENGINEERING',
        team_zh: '工程团队',
        label: 'March 2026',
        label_zh: '2026年3月',
        bg: 'url(img/blog-release-nightly.png) center/cover no-repeat',
        related: ['ann-beta', 'ann-v010', 'ann-v014'],
        sections: [
          { type: 'p', text: 'Automated desktop build.' },
          { type: 'p', text: '<strong>Version:</strong> 0.1.3<br><strong>Environment:</strong> test<br><strong>Commit:</strong> c5fb86e9ff38ae7b18ac00dd19d5350834602651<br><strong>Built:</strong> 20260319' },
          { type: 'p', text: 'The packaged Nexu.app bundle is notarized and stapled.' },
          { type: 'p', text: 'This build is intended for testing and may be unstable.' },
          { type: 'h2', text: 'Three Release Channels' },
          { type: 'p', text: 'We maintain three release channels: <strong>Nightly</strong> (latest code, may be unstable) for developers who want to follow along closely. <strong>Beta</strong> (feature-complete, needs testing) for power users who want early access. <strong>Stable</strong> (production-ready) for daily business use.' },
          { type: 'h2', text: 'How to Use It' },
          { type: 'p', text: 'Download the nightly .dmg from our <a class="blog-link" href="https://github.com/nexu-io/nexu/releases">GitHub releases page</a>, install it alongside your stable version, and report any issues you find.' }
        ],
        sections_zh: [
          { type: 'p', text: '自动化桌面构建。' },
          { type: 'p', text: '<strong>版本号：</strong>0.1.3<br><strong>环境：</strong>test<br><strong>Commit：</strong>c5fb86e9ff38ae7b18ac00dd19d5350834602651<br><strong>构建日期：</strong>20260319' },
          { type: 'p', text: '打包的 Nexu.app 已通过 Apple 公证和签章。' },
          { type: 'p', text: '此构建用于测试，可能不稳定。' },
          { type: 'h2', text: '三个发布渠道' },
          { type: 'p', text: '我们现在有三个发布渠道：<strong>Nightly</strong> 包含最新代码，可能不太稳定，适合想紧跟开发节奏的人；<strong>Beta</strong> 功能已开发完成，还在做最后测试，适合想抢先体验的用户；<strong>Stable</strong> 是经过完整测试的正式版，适合日常工作使用。' },
          { type: 'h2', text: '怎么使用' },
          { type: 'p', text: '从 <a class="blog-link" href="https://github.com/nexu-io/nexu/releases">GitHub Releases</a> 下载 Nightly .dmg，和稳定版并行安装就行。使用过程中发现问题，随时反馈给我们。' }
        ]
      },
      {
        id: 'ann-beta',
        category: 'Announcements',
        slug: 'nexu-desktop-beta-channel',
        title: 'nexu v0.1.5-beta: Desktop Beta Channel Is Live',
        title_zh: 'nexu v0.1.5-beta：Desktop Beta 渠道上线',
        desc: 'The nexu beta channel is live — a notarized macOS build with upcoming features ready for community testing before stable release.',
        desc_zh: 'nexu Beta 渠道正式开放——功能已开发完成，经过 Apple 公证，在正式发布前邀请社区用户抢先测试。',
        date: "MAR 19 '26",
        date_zh: '2026年3月19日',
        team: 'ENGINEERING',
        team_zh: '工程团队',
        label: 'March 2026',
        label_zh: '2026年3月',
        bg: 'url(img/blog-release-beta.png) center/cover no-repeat',
        related: ['ann-nightly', 'ann-v015', 'ann-v014'],
        sections: [
          { type: 'p', text: 'Automated desktop build.' },
          { type: 'p', text: '<strong>Version:</strong> 0.1.5-beta.20260323<br><strong>Channel:</strong> beta<br><strong>Environment:</strong> nexu-prod<br><strong>Commit:</strong> e2e33d87321c4255a06bac69928952cd8ae88c83<br><strong>Built:</strong> 20260323' },
          { type: 'p', text: 'The packaged Nexu.app bundle is notarized and stapled.' },
          { type: 'p', text: 'This build is intended for testing and may be unstable.' },
          { type: 'h2', text: 'How to Join the Beta' },
          { type: 'p', text: 'Download the beta .dmg from the <a class="blog-link" href="https://github.com/nexu-io/nexu/releases">GitHub releases page</a> (tagged desktop-beta). Install it like any other version. If you run into issues, file them on GitHub — your feedback directly shapes what ships in stable.' }
        ],
        sections_zh: [
          { type: 'p', text: '自动化桌面构建。' },
          { type: 'p', text: '<strong>版本号：</strong>0.1.5-beta.20260323<br><strong>渠道：</strong>beta<br><strong>环境：</strong>nexu-prod<br><strong>Commit：</strong>e2e33d87321c4255a06bac69928952cd8ae88c83<br><strong>构建日期：</strong>20260323' },
          { type: 'p', text: '打包的 Nexu.app 已通过 Apple 公证和签章。' },
          { type: 'p', text: '此构建用于测试，可能不稳定。' },
          { type: 'h2', text: '怎么参与 Beta 测试' },
          { type: 'p', text: '从 <a class="blog-link" href="https://github.com/nexu-io/nexu/releases">GitHub Releases</a> 下载标签为 desktop-beta 的 .dmg 安装包，像装普通应用一样安装即可。使用中遇到问题，欢迎在 GitHub 提 issue——你的反馈会直接影响正式版的最终质量。' }
        ]
      },
      {
        id: 'ann-v014',
        category: 'Announcements',
        slug: 'nexu-v014-wechat-skills',
        title: 'nexu v0.1.4: WeChat Support, Skill Management & New Local Runtime',
        title_zh: 'nexu v0.1.4：支持微信、重构 Skill 管理、全新本地运行时',
        desc: 'v0.1.4 brings WeChat QR-code login, a controller-first local runtime, curated Skill installs with Chinese localization, and 40+ bug fixes.',
        desc_zh: 'v0.1.4 新增微信扫码连接、全新本地运行时架构、中文 Skill 商店，以及 40 多项 Bug 修复。',
        date: "MAR 22 '26",
        date_zh: '2026年3月22日',
        team: 'ENGINEERING',
        team_zh: '工程团队',
        label: 'March 2026',
        label_zh: '2026年3月',
        bg: 'url(img/blog-release-v014.png) center/cover no-repeat',
        related: ['ann-v015', 'ann-v010', 'featured'],
        sections: [
          { type: 'h2', text: '✨ New Features' },
          { type: 'p', text: 'Better skill management: curated installs, Chinese catalog localization, lowdb skill ledger, and catalog/package fixes (#267, #288, #317, #323).' },
          { type: 'p', text: 'New controller-first local runtime with OpenClaw config push, readiness feedback, and model-routing templates (#269, #274, #320).' },
          { type: 'p', text: 'New WeChat support with QR-code login, plus bundled image/audio/browser skills (#324, #326, #270).' },
          { type: 'p', text: 'Better product UI: session chat history, updated auth page, improved sidebar, restored provider icons, and desktop build metadata (#278, #309, #252, #314, #257, #290).' },
          { type: 'p', text: 'Better release and debug tooling: Slack reply probe, desktop diagnostics export, and improved release channel/artifact handling (#272, #289, #266, #338, #337).' },
          { type: 'h2', text: '🐛 Bug Fixes' },
          { type: 'p', text: 'Fixed packaged desktop skill installs and several startup/reconnect issues across local and cloud flows (#240, #237, #241, #247, #261, #256, #265).' },
          { type: 'p', text: 'Fixed desktop polish issues including sleep handling, drag bar spacing, traffic-light alignment, icons, and diagnostics/Sentry setup (#299, #316, #313, #291, #253, #287, #301, #303).' },
          { type: 'p', text: 'Fixed web/product issues including BYOK saved-state messaging, privacy/terms links, docs links, model list cleanup, and skill content rendering (#260, #259, #271, #282, #315, #294).' },
          { type: 'p', text: 'Fixed runtime and packaging issues by restoring local dev flow, switching to sql.js, speeding postinstall, preserving sharp paths, and stabilizing WeChat plugin config (#295, #298, #318, #330, #329).' },
          { type: 'p', text: 'Fixed channel and UX issues in Feishu fallback handling, Slack model routing, browser open-folder flow, and WeChat session/sidebar behavior (#319, #268, #309, #340).' },
          { type: 'h2', text: '🧹 Maintenance & Cleanup' },
          { type: 'p', text: 'Removed deprecated API/gateway/deploy paths, the apps/landing package, the router workspace, and old skills-catalog APIs (#296, #254, #325, #292).' },
          { type: 'p', text: 'Cleaned up release plumbing with refreshed runtime metadata, v tag support, safer release scripting, and final v0.1.4 prep (#332, #338, #341, #333, #342).' },
          { type: 'h2', text: '🙌 New Contributors' },
          { type: 'p', text: '@qiongyu1999 made their first contribution in #248. @ashleyashli made their first contribution in #310.' },
          { type: 'p', text: 'Full Changelog: <a class="blog-link" href="https://github.com/nexu-io/nexu/compare/v0.1.0...v0.1.4">v0.1.0...v0.1.4</a>' }
        ],
        sections_zh: [
          { type: 'h2', text: '✨ 新功能' },
          { type: 'p', text: '更好的 Skill 管理：精选安装、中文目录本地化、lowdb Skill 账本、目录/包稳定性修复（#267, #288, #317, #323）。' },
          { type: 'p', text: '新 Controller-First 本地运行时，支持 OpenClaw 配置推送、就绪反馈、模型路由模板（#269, #274, #320）。' },
          { type: 'p', text: '新增微信支持，QR 扫码登录，附带图片/音频/浏览器技能（#324, #326, #270）。' },
          { type: 'p', text: '产品 UI 改进：会话聊天记录、更新的认证页、改进的侧边栏、恢复供应商图标、桌面构建元数据（#278, #309, #252, #314, #257, #290）。' },
          { type: 'p', text: '发布和调试工具改进：Slack 回复探测、桌面诊断导出、改进的发布渠道/构建物处理（#272, #289, #266, #338, #337）。' },
          { type: 'h2', text: '🐛 Bug 修复' },
          { type: 'p', text: '修复打包桌面 Skill 安装和多个本地/云端启动/重连问题（#240, #237, #241, #247, #261, #256, #265）。' },
          { type: 'p', text: '修复桌面细节问题：休眠处理、拖动条间距、红绿灯对齐、图标、诊断/Sentry 配置（#299, #316, #313, #291, #253, #287, #301, #303）。' },
          { type: 'p', text: '修复 Web/产品问题：BYOK 保存状态消息、隐私/条款链接、文档链接、模型列表清理、Skill 内容渲染（#260, #259, #271, #282, #315, #294）。' },
          { type: 'p', text: '修复运行时和打包问题：恢复本地开发流程、切换 sql.js、加速 postinstall、保留 sharp 路径、稳定微信插件配置（#295, #298, #318, #330, #329）。' },
          { type: 'p', text: '修复渠道和 UX 问题：飞书回退处理、Slack 模型路由、浏览器打开文件夹、微信会话/侧边栏行为（#319, #268, #309, #340）。' },
          { type: 'h2', text: '🧹 维护与清理' },
          { type: 'p', text: '移除废弃的 API/网关/部署路径、apps/landing 包、路由工作区、旧 skills-catalog API（#296, #254, #325, #292）。' },
          { type: 'p', text: '清理发布流程：刷新运行时元数据、v 标签支持、更安全的发布脚本、v0.1.4 最终准备（#332, #338, #341, #333, #342）。' },
          { type: 'h2', text: '🙌 新贡献者' },
          { type: 'p', text: '@qiongyu1999 在 #248 中做出了首次贡献。@ashleyashli 在 #310 中做出了首次贡献。' },
          { type: 'p', text: '完整变更日志：<a class="blog-link" href="https://github.com/nexu-io/nexu/compare/v0.1.0...v0.1.4">v0.1.0...v0.1.4</a>' }
        ]
      },
      {
        id: 'ann-v015',
        category: 'Announcements',
        slug: 'nexu-v015-skill-import',
        title: 'nexu v0.1.5: Skill Import, Richer Chat & Fewer Zombies',
        title_zh: 'nexu v0.1.5：Skill 导入、Markdown 聊天、告别僵尸进程',
        desc: 'v0.1.5 adds Skill zip import, markdown rendering in chat, dynamic runtime ports, and kills the zombie process and Feishu restart bugs.',
        desc_zh: 'v0.1.5 支持通过 zip 导入 Skill、聊天支持 Markdown 渲染、运行时端口动态分配，修复了僵尸进程和飞书重启死循环。',
        date: "MAR 23 '26",
        date_zh: '2026年3月23日',
        team: 'ENGINEERING',
        team_zh: '工程团队',
        label: 'March 2026',
        label_zh: '2026年3月',
        bg: 'url(img/blog-release-v015.png) center/cover no-repeat',
        related: ['ann-v014', 'ann-beta', 'featured'],
        sections: [
          { type: 'h2', text: '✨ New Features' },
          { type: 'p', text: '<strong>Skill import modal:</strong> Import Skill dialog with zip upload support and bilingual UI. (#355)' },
          { type: 'p', text: '<strong>Markdown chat rendering:</strong> Session chat bubbles now render formatted content — lists, links, code blocks. (#348)' },
          { type: 'p', text: '<strong>Dynamic runtime ports:</strong> Desktop runtime allocates ports dynamically, eliminating fixed-port conflicts on startup. (#331)' },
          { type: 'p', text: '<strong>About dialog & update menu:</strong> Added app About dialog and in-app update check actions. (#345)' },
          { type: 'p', text: '<strong>Workspace & runtime analytics:</strong> Added analytics events for workspace and runtime lifecycle tracking. (#411)' },
          { type: 'h2', text: '🐛 Bug Fixes' },
          { type: 'p', text: '<strong>Fix Feishu restart loop:</strong> Config writer now skips redundant writes, breaking the restart → syncAll → write → watcher cycle that made Feishu channels unusable. (#347)' },
          { type: 'p', text: '<strong>Fix zombie processes on quit:</strong> App quit now awaits child process cleanup and escalates to SIGKILL after 3s, preventing orphaned processes that block app deletion. (#346)' },
          { type: 'p', text: '<strong>Fix cold-start config reload:</strong> Config writer seeds its cache from disk on startup, avoiding unnecessary OpenClaw reloads after every controller restart. (#349)' },
          { type: 'p', text: '<strong>Fix channel-aware update checks:</strong> Updater now checks the correct feed URL for stable/beta/nightly channels. (#345)' },
          { type: 'p', text: '<strong>Fix webview mount crash:</strong> Set webview src via JSX prop to prevent null-src crash on initial mount. (#407)' },
          { type: 'p', text: '<strong>Fix skill card drag:</strong> Prevent drag event on skill cards from opening a second browser window. (#361)' },
          { type: 'p', text: '<strong>Fix controller symlink crash:</strong> Filter out node_modules/.bin symlinks during runtime plugin copy to prevent EINVAL on skill import. (#355)' },
          { type: 'h2', text: '🙌 New Contributors' },
          { type: 'p', text: '@NickHood1984 made their first contribution in #348. @zoeforfun made their first contribution in #418.' },
          { type: 'p', text: 'Full Changelog: <a class="blog-link" href="https://github.com/nexu-io/nexu/compare/v0.1.4...v0.1.5">v0.1.4...v0.1.5</a>' }
        ],
        sections_zh: [
          { type: 'h2', text: '✨ 新功能' },
          { type: 'p', text: '<strong>Skill 导入弹窗：</strong>支持 zip 上传的 Skill 导入对话框，双语 UI。（#355）' },
          { type: 'p', text: '<strong>Markdown 聊天渲染：</strong>会话聊天气泡支持渲染格式化内容——列表、链接、代码块。（#348）' },
          { type: 'p', text: '<strong>动态运行时端口：</strong>桌面运行时动态分配端口，消除启动时的固定端口冲突。（#331）' },
          { type: 'p', text: '<strong>关于对话框 & 更新菜单：</strong>新增应用关于对话框和应用内更新检查。（#345）' },
          { type: 'p', text: '<strong>工作区 & 运行时分析：</strong>新增工作区和运行时生命周期追踪分析事件。（#411）' },
          { type: 'h2', text: '🐛 Bug 修复' },
          { type: 'p', text: '<strong>修复飞书重启死循环：</strong>配置写入器跳过冗余写入，打破 restart → syncAll → write → watcher 循环，该循环导致飞书渠道不可用。（#347）' },
          { type: 'p', text: '<strong>修复退出后僵尸进程：</strong>应用退出时等待子进程清理，3 秒后升级为 SIGKILL，防止孤儿进程阻止应用删除。（#346）' },
          { type: 'p', text: '<strong>修复冷启动配置重载：</strong>配置写入器从磁盘种子缓存，避免每次控制器重启后不必要的 OpenClaw 重载。（#349）' },
          { type: 'p', text: '<strong>修复渠道感知更新检查：</strong>更新器现在检查 stable/beta/nightly 渠道对应的正确 feed URL。（#345）' },
          { type: 'p', text: '<strong>修复 webview 挂载崩溃：</strong>通过 JSX prop 设置 webview src，防止初始挂载时 null-src 崩溃。（#407）' },
          { type: 'p', text: '<strong>修复 Skill 卡片拖拽：</strong>阻止 Skill 卡片上的拖拽事件打开第二个浏览器窗口。（#361）' },
          { type: 'p', text: '<strong>修复控制器符号链接崩溃：</strong>在运行时插件复制时过滤 node_modules/.bin 符号链接，防止 Skill 导入时 EINVAL 错误。（#355）' },
          { type: 'h2', text: '🙌 新贡献者' },
          { type: 'p', text: '@NickHood1984 在 #348 中做出了首次贡献。@zoeforfun 在 #418 中做出了首次贡献。' },
          { type: 'p', text: '完整变更日志：<a class="blog-link" href="https://github.com/nexu-io/nexu/compare/v0.1.4...v0.1.5">v0.1.4...v0.1.5</a>' }
        ]
      },
`;

html = before + newArticles + '      ' + after;

fs.writeFileSync(path.join(__dirname, 'site/blog.html'), html, 'utf-8');
console.log('Done. Featured article + 5 announcements replaced. Guide articles preserved.');
